# Generated by Django 5.1.1 on 2024-10-13 16:36

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('jugador_id', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('pais', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Puntuacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuaciones', models.PositiveBigIntegerField()),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('dias', models.PositiveSmallIntegerField()),
                ('isTheBest', models.BooleanField()),
                ('recursos_criticos', models.JSONField(blank=True, default=dict)),
                ('jugador_id', models.ForeignKey(db_column='jugador_ID', on_delete=django.db.models.deletion.CASCADE, related_name='puntajes', to='Loggin.jugador')),
            ],
        ),
    ]
