# Generated by Django 5.1.1 on 2024-10-13 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Loggin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eventos_Base',
            fields=[
                ('evento_id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('elementos_afectados', models.JSONField(blank=True, default=dict)),
            ],
        ),
    ]
