# Generated by Django 5.1.1 on 2024-10-13 15:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('fechaRegistro', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
